Document: serval-dna
Title: Debian serval-dna Manual
Author: <insert document author here>
Abstract: This manual describes what serval-dna is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/serval-dna/serval-dna.sgml.gz

Format: postscript
Files: /usr/share/doc/serval-dna/serval-dna.ps.gz

Format: text
Files: /usr/share/doc/serval-dna/serval-dna.text.gz

Format: HTML
Index: /usr/share/doc/serval-dna/html/index.html
Files: /usr/share/doc/serval-dna/html/*.html
